application: empatika-doubleb
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /(admin/(audio|css|images|js)/.*)
  static_files: static/\1
  upload: static/admin/.*

- url: /docs
  static_dir: static/docs

- url: /static
  static_dir: static

- url: /cron/.*
  script: handlers.cron.app
  login: admin

- url: /mt/.*
  script: main.app
  login: admin

- url: /admin/signup
  script: main.app
  login: admin

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: latest

- name: jinja2
  version: latest

builtins:
- remote_api: on

