application: doubleb-automation-production
version: test2
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /(admin/(audio|css|images|js)/.*)
  static_files: static/\1
  upload: static/admin/.*

- url: /static/(.*\.manifest)
  static_files: static/\1
  upload: static/.*\.manifest
  mime_type: text/cache-manifest

- url: /static
  static_dir: static
  expiration: 1s

- url: /images
  static_dir: images

- url: /cron/.*
  script: handlers.cron.app
  login: admin

- url: /mt/.*
  script: main.app
  login: admin

- url: /admin/signup
  script: main.app
  login: admin

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: latest

- name: PIL
  version: "1.1.7"

- name: jinja2
  version: latest

- name: lxml
  version: "latest"

builtins:
- remote_api: on
- deferred: on

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^node_modules/.*
- ^frontend-src/.*
